// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OleszekMowinski.ProjectApp.DAOSQL;

#nullable disable

namespace OleszekMowinski.ProjectApp.DAOSQL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231211212507_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OleszekMowinski.ProjectApp.DAOEF.DataObjects.Airplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Introduction")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManufacturerIdEF")
                        .HasColumnType("TEXT")
                        .HasColumnName("ManufacturerIdEF");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerIdEF");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("OleszekMowinski.ProjectApp.DAOEF.DataObjects.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("OleszekMowinski.ProjectApp.DAOEF.DataObjects.Airplane", b =>
                {
                    b.HasOne("OleszekMowinski.ProjectApp.DAOEF.DataObjects.Manufacturer", "Manufacturer")
                        .WithMany("Airplanes")
                        .HasForeignKey("ManufacturerIdEF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("OleszekMowinski.ProjectApp.DAOEF.DataObjects.Manufacturer", b =>
                {
                    b.Navigation("Airplanes");
                });
#pragma warning restore 612, 618
        }
    }
}
